language : node_js
node_js :
  - stable
cache: npm
script:
  - npm run test-with-cover
# Send coverage data to Coveralls
after_success:
  - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"